import type { Metadata } from "next";
import { Poppins, Poltawski_Nowy, IBM_Plex_Mono} from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

const poltawski = Poltawski_Nowy({
  variable: "--font-poltawaski",
  subsets: ["latin"],
});

const plex = IBM_Plex_Mono({
  variable: "--font-plex",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600",]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plex.variable} ${poltawski.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
